FORMULA_SHEET = {
    "physics": {
        "ohm_law": "V = I × R",
        "power": "P = V × I",
        "force": "F = m × a",
        "kinetic_energy": "KE = 1/2 × m × v²",
        "kinematic_1": "v = u + at",
        "kinematic_2": "s = ut + 1/2 at²",
        "kinematic_3": "v² = u² + 2as",
        "momentum": "p = m × v",
        "gravitational_potential": "PE = m × g × h",
        "centripetal_force": "F = m × v²/r",
        "period_frequency": "T = 1/f",
        "lens_equation": "1/f = 1/v - 1/u",
        "ideal_gas": "P × V = n × R × T",
        "wave_speed": "v = f × λ",
        "angular_speed": "ω = θ/t",
        "angular_momentum": "L = Iω",
        "torque": "τ = rF sin(θ)",
        "rotational_kinetic_energy": "KE_rot = 1/2 Iω²",
        "rolling_energy": "v = rω",
        "spring_force": "F = -kx",
        "shm_period": "T = 2π√(m/k)",
        "pendulum_period": "T = 2π√(L/g)",
        "gravitational_force": "F = Gm₁m₂/r²",
        "impulse": "J = Δp = FΔt",
        "work": "W = Fd cos(θ)",
        "power_average": "P = W/t",
        "wave_frequency": "f = 1/T",
        "standing_wave": "L = nλ/2",
        "doppler": "f' = f(v ± vₒ)/(v ∓ vₛ)",
        "refractive_index": "n = c/v",
        "snell_law": "n₁ sin(θ₁) = n₂ sin(θ₂)",
        "lens_magnification": "m = v/u = hᵢ/hₒ",
        "electric_field": "E = F/q = kQ/r²",
        "electric_potential": "V = kQ/r",
        "capacitor": "Q = CV",
        "capacitor_energy": "U = 1/2 CV²",
        "kirchhoff_current": "ΣI_in = ΣI_out",
        "kirchhoff_voltage": "ΣV = 0",
        "magnetic_force": "F = qvB sin(θ)",
        "wire_force": "F = BIL sin(θ)",
        "faraday_law": "ε = -dΦ/dt",
        "transformer": "Vₚ/Vₛ = Nₚ/Nₛ",
        "mass_energy": "E = mc²",
        "radioactive_decay": "N = N₀e^(-λt)",
        "half_life": "t₁/₂ = ln(2)/λ",
    },
    "chemistry": {
        "ideal_gas": "PV = nRT",
        "molar_mass": "M = mass / moles",
        "percent_yield": "% yield = actual / theoretical × 100",
        "concentration": "C = n / V",
        "moles": "n = mass / molar mass",
        "dilution": "C₁V₁ = C₂V₂",
        "molality": "m = moles solute / kg solvent",
        "ph": "pH = -log₁₀[H⁺]",
        "poh": "pOH = -log₁₀[OH⁻]",
        "henderson_hasselbalch": "pH = pKa + log([base]/[acid])",
        "rate": "rate = change in concentration / time",
        "gibbs": "ΔG = ΔH - TΔS",
        "nernst": "E = E° - (RT/nF) ln Q",
        "density": "ρ = m/V",
        "mole_fraction": "χᵢ = nᵢ/Σn",
        "gas_combined": "P₁V₁/T₁ = P₂V₂/T₂",
        "dalton": "P_total = ΣPᵢ",
        "arrhenius": "k = Ae^(-Eₐ/RT)",
        "first_order": "ln[A] = ln[A]₀ - kt",
        "second_order": "1/[A] = 1/[A]₀ + kt",
        "equilibrium": "Kc = [products]/[reactants]",
        "gibbs_equilibrium": "ΔG° = -RT ln K",
        "osmotic_pressure": "Π = iMRT",
        "freezing_point": "ΔT_f = iK_fm",
        "boiling_point": "ΔT_b = iK_bm",
        "cell_potential": "E°cell = E°cathode - E°anode",
        "faradays_electrolysis": "m = ItM/(nF)",
        "heat": "q = mcΔT",
        "enthalpy": "ΔH = H_products - H_reactants",
        "beer_lambert": "A = εbc",
    },
    "math": {
        "quadratic": "x = (-b ± √(b² - 4ac)) / 2a",
        "slope": "m = (y₂ - y₁) / (x₂ - x₁)",
        "area_circle": "A = πr²",
        "volume_sphere": "V = 4/3 πr³",
        "distance": "d = √((x₂-x₁)² + (y₂-y₁)²)",
        "pythagoras": "a² + b² = c²",
        "triangle_area": "A = 1/2 × base × height",
        "circumference": "C = 2πr",
        "derivative_power": "d(xⁿ)/dx = n×xⁿ⁻¹",
        "integral_power": "∫xⁿdx = xⁿ⁺¹/(n+1) + C",
        "mean": "mean = Σx / n",
        "probability": "P(A) = favourable outcomes / total outcomes",
        "compound_interest": "A = P(1 + r/n)ⁿᵗ",
        "linear_equation": "ax + b = 0 → x = -b/a",
        "arithmetic_sequence": "a_n = a₁ + (n-1)d",
        "arithmetic_sum": "S_n = n/2[2a₁ + (n-1)d]",
        "geometric_sequence": "a_n = arⁿ⁻¹",
        "geometric_sum": "S_n = a(rⁿ-1)/(r-1)",
        "binomial": "(a+b)ⁿ = Σ C(n,r)aⁿ⁻ʳbʳ",
        "circle_equation": "(x-h)² + (y-k)² = r²",
        "parabola": "y-k = a(x-h)²",
        "ellipse": "(x-h)²/a² + (y-k)²/b² = 1",
        "vector_magnitude": "|v| = √(vₓ² + vᵧ² + v_z²)",
        "dot_product": "a·b = |a||b|cos(θ)",
        "cross_product": "|a×b| = |a||b|sin(θ)",
        "chain_rule": "d/dx f(g(x)) = f'(g(x))g'(x)",
        "product_rule": "(fg)' = f'g + fg'",
        "quotient_rule": "(f/g)' = (f'g - fg')/g²",
        "fundamental_theorem": "∫ₐᵇ f(x)dx = F(b)-F(a)",
        "binomial_probability": "P(X=k) = C(n,k)pᵏ(1-p)ⁿ⁻ᵏ",
        "expected_value": "E(X) = ΣxP(x)",
        "variance": "Var(X) = E(X²) - [E(X)]²",
        "standard_deviation": "σ = √Var(X)",
        "z_score": "z = (x-μ)/σ",
        "permutation": "P(n,r) = n!/(n-r)!",
        "combination": "C(n,r) = n!/[r!(n-r)!]",
    },
    "computer_science": {
        "binary_search": "T(n) = O(log n)",
        "linear_search": "T(n) = O(n)",
        "merge_sort": "T(n) = O(n log n)",
        "tree_height": "h = log₂(n+1) - 1 (balanced)",
        "bytes_bits": "1 byte = 8 bits",
        "throughput": "throughput = work/time",
    },
}


def get_formula_group(group_name):
    return FORMULA_SHEET.get(group_name.lower(), {})
